SOLUTION OF NUMPY SECTION OF PYTHON IN HACKER RANK

queston 1: np- array
link-https://www.hackerrank.com/challenges/np-arrays/problem


In [2]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    
    return numpy.array(arr[::-1],float)
    

arr = input().strip().split(' ')
print(arrays(arr))

1 2 3 4 5 6
[6. 5. 4. 3. 2. 1.]


question 2: np- shape-reshape
link-https://www.hackerrank.com/challenges/np-shape-reshape/problem

In [3]:
import numpy as np

b=input().strip().split(" ")
b=np.array(b,int)
b.shape=(3,3)
print(b)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


question 3:Transpose and Flatten
link-https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem

In [4]:
import numpy as np
n,m=map(int,input().split())
b=np.array([input().split() for i in range(n)],int)
print(np.transpose(b))
print(b.flatten())

3 2
2 3 
3 4
5 3
[[2 3 5]
 [3 4 3]]
[2 3 3 4 5 3]


question 4:Concatenate
link-https://www.hackerrank.com/challenges/np-concatenate/problem    

In [5]:
import numpy 
n,m,p=map(int,input().split(" "))
a=numpy.array([input().split() for i in range(n)],int)
b=numpy.array([input().split() for i in range(m)],int)
print(numpy.concatenate((a,b)))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


question 5-Zeros and Ones
link-https://www.hackerrank.com/challenges/np-zeros-and-ones/problem

In [7]:
import numpy
#touple is used cz input can be of more than 3d as well

n = tuple(map(int,input().split()))
print(numpy.zeros((n),dtype=numpy.int))
print(numpy.ones((n),dtype=numpy.int))


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


question 5-Eye and Identity
link-https://www.hackerrank.com/challenges/np-eye-and-identity/problem

In [8]:
import numpy
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


question 6-Array Mathematics
link-https://www.hackerrank.com/challenges/np-array-mathematics/problem

In [11]:
import numpy
n,m=map(int,input().split())
a=numpy.array([input().split() for i in range(n)],int)
b=numpy.array([input().split() for i in range(n)],int)
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(a**b)



1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


question 7-Floor, Ceil and Rint
link-https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem

In [10]:
import numpy
numpy.set_printoptions(sign=' ')
b=list(map(float,input().split()))
b=numpy.array(b,float)
print(numpy.floor(b))
print(numpy.ceil(b))
print(numpy.rint(b))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


question 8-Sum and Prod
link-https://www.hackerrank.com/challenges/np-sum-and-prod/problem

In [12]:
import numpy

n,m=map(int,input().split())
a=numpy.array([input().split() for i in range(n)],int)
print(numpy.prod(numpy.sum(a,axis=0),axis=0))


2 2
1 2
3 4
24


question 9-Min and Max
link-https://www.hackerrank.com/challenges/np-min-and-max/problem

In [13]:
import numpy

n,m=map(int,input().split())
a=numpy.array([input().split() for i in range(n)],int)

print(numpy.max(numpy.min((a),axis=1)))

4 2
2 5
3 7
1 3
4 0
3


question 10-Mean, Var, and Std
link- https://www.hackerrank.com/challenges/np-mean-var-and-std/problem

In [15]:
import numpy as np
n,m=map(int,input().split())
c=np.array([input().split() for i in range(n)],int)
numpy.set_printoptions(legacy='1.13')
print(np.mean(c,axis=1))
print(np.var(c,axis=0))
print(np.std(c))


2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


question 11-Dot and Cross
link-https://www.hackerrank.com/challenges/np-dot-and-cross/problem


In [18]:
import numpy as np
n=int(input())
a=np.array([input().split() for i in range(n)],int)
b=np.array([input().split() for i in range(n)],int)
print(np.dot(a,b))

2 
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


question 12-Inner and Outer
link-https://www.hackerrank.com/challenges/np-inner-and-outer/problem

In [19]:
import numpy

b=input().split()
c=input().split()
A=numpy.array(b,int)
B=numpy.array(c,int)
print(numpy.inner(A, B)) 
print(numpy.outer(A, B))


0 1
2 3
3
[[0 0]
 [2 3]]


question 13-Polynomials
link-https://www.hackerrank.com/challenges/np-polynomials/problem

In [21]:
import numpy

n=numpy.array(input().split(),float)
b=float(input())
print(numpy.polyval(n,b))



1.1 2 3
0
3.0


question 14-Linear Algebra
link-https://www.hackerrank.com/challenges/np-linear-algebra/problem

In [23]:
import numpy
n=int(input())
b=numpy.array([input().split() for i in range(n)]) 
print(b)

2
1.1 1.1
1.1 1.1
[['1.1' '1.1']
 ['1.1' '1.1']]
